export const bearsLoveDefiAbi = [
	{
		type: "constructor",
		inputs: [
			{ name: "_memeToken", type: "address", internalType: "address" },
			{ name: "_nftContract", type: "address", internalType: "address" },
			{ name: "_threshold", type: "uint256", internalType: "uint256" },
		],
		stateMutability: "nonpayable",
	},
	{ type: "receive", stateMutability: "payable" },
	{
		type: "function",
		name: "checkClaimableMeme",
		inputs: [{ name: "account", type: "address", internalType: "address" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{ type: "function", name: "claimMeme", inputs: [], outputs: [], stateMutability: "nonpayable" },
	{
		type: "function",
		name: "holders",
		inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "memeClaims",
		inputs: [{ name: "", type: "address", internalType: "address" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "memeToken",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "contract BearsLoveMemes" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "nftContract",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "contract BearsLoveMountains" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "nftHoldings",
		inputs: [{ name: "", type: "address", internalType: "address" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "owner",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{ type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
	{
		type: "function",
		name: "setNftContract",
		inputs: [{ name: "_nftContract", type: "address", internalType: "address" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "threshold",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "totalCirculation",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "transferOwnership",
		inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "updateTotals",
		inputs: [
			{ name: "account", type: "address", internalType: "address" },
			{ name: "amount", type: "uint256", internalType: "uint256" },
			{ name: "isMinting", type: "bool", internalType: "bool" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{ type: "function", name: "withdraw", inputs: [], outputs: [], stateMutability: "nonpayable" },
	{
		type: "event",
		name: "BearsLoveDefi_TokensPurchased",
		inputs: [
			{ name: "ethAmount", type: "uint256", indexed: false, internalType: "uint256" },
			{ name: "memeAmount", type: "uint256", indexed: false, internalType: "uint256" },
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "MemeCoinsDistributed",
		inputs: [{ name: "totalMemeAmount", type: "uint256", indexed: false, internalType: "uint256" }],
		anonymous: false,
	},
	{
		type: "event",
		name: "OwnershipTransferred",
		inputs: [
			{ name: "previousOwner", type: "address", indexed: true, internalType: "address" },
			{ name: "newOwner", type: "address", indexed: true, internalType: "address" },
		],
		anonymous: false,
	},
	{
		type: "error",
		name: "OwnableInvalidOwner",
		inputs: [{ name: "owner", type: "address", internalType: "address" }],
	},
	{
		type: "error",
		name: "OwnableUnauthorizedAccount",
		inputs: [{ name: "account", type: "address", internalType: "address" }],
	},
] as const;
